export const allData = [
  {
    id: 1,
    productCode: "7001",
    category: "bag",
    subCategory: "officeBag",
    price: 2700,
    img: "",
  },
  {
    id: 2,
    productCode: "7002",
    category: "bag",
    subCategory: "officeBag",
    price: 2700,
    img: "",
  },
  {
    id: 3,
    productCode: "7003",
    category: "bag",
    subCategory: "gymBag",
    price: 2700,
    img: "",
  },
  {
    id: 4,
    productCode: "7004",
    category: "bag",
    subCategory: "gymbag",
    price: 2700,
    img: "",
  },
  {
    id: 5,
    productCode: "7005",
    category: "bag",
    subCategory: "womenBag",
    price: 2700,
    img: "",
  },
  {
    id: 6,
    productCode: "7006",
    category: "bag",
    subCategory: "womenBag",
    price: 2700,
    img: "",
  },
  {
    id: 7,
    productCode: "7007",
    category: "bag",
    subCategory: "laptopBag",
    price: 2700,
    img: "",
  },
  {
    id: 8,
    productCode: "7008",
    category: "bag",
    subCategory: "LaptopBag",
    price: 2700,
    img: "",
  },
  {
    id: 9,
    productCode: "7009",
    category: "shoe",
    subCategory: "menShoe",
    price: 2700,
    img: "",
  },
  {
    id: 10,
    productCode: "70010",
    category: "shoe",
    subCategory: "menShoe",
    price: 2700,
    img: "",
  },
  {
    id: 11,
    productCode: "70011",
    category: "shoe",
    subCategory: "WomenShoe",
    price: 2700,
    img: "",
  },
  {
    id: 12,
    productCode: "70012",
    category: "shoe",
    subCategory: "womenShoe",
    price: 2700,
    img: "",
  },
];
