// this is ladis Bag
export const womenBag = [
  {
    id: 1,
    productCode: "FSB-002",
    category: "bag",
    subCategory: "officeBag",
    price: 1000.0,
    img: "https://i.imgur.com/20FMklB.jpg",
    description:
      "Exclusive Ladies Hand Bag | 100% Leather & Cotton Fabrics | Very High Quality",
    color: "Blue Color Leather with Designer Fabrics",
    size: " H x W - 15' x 16' ",
  },
  {
    id: 2,
    productCode: "LCB-0002J",
    category: "bag",
    subCategory: "officeBag",
    price: 1800.0,
    img: "https://i.imgur.com/ON15Qxt.jpg",
    description:
      "Exclusive Ladies Hand Bag | 100% Leather & Cotton Fabrics | Very High Quality",
    color: "Brown Designer Leather with Black Color Leather",
    size: "  H x W - 12.5' x 9.5' ",
  },
  {
    id: 3,
    productCode: "BBG-7030",
    category: "bag",
    subCategory: "officeBag",
    price: 2700.0,
    img: "https://i.imgur.com/oif0I5M.jpg",
    description:
      "Exclusive Ladies Hand Bag | 100% Leather & Cotton Fabrics | Very High Quality",
    color: "Red Wine with Blue Leather",
    size: "  H x W x L - 10' x 14' x 5' ",
  },
  {
    id: 4,
    productCode: "VCB-603",
    category: "bag",
    subCategory: "officeBag",
    price: 1200.0,
    img: "https://i.imgur.com/3gRmyXp.jpg",
    description:
      "Exclusive Ladies Party Bag | 100% Leather & Cotton Fabrics | Very High Quality",
    color: "red",
    size: " H x W x L - 7' x 8' x 4' ",
  },
  {
    id: 5,
    productCode: "LTB-004",
    category: "bag",
    subCategory: "officeBag",
    price: 1790.0,
    img: "https://i.imgur.com/dZIzFgP.jpg",
    description:
      "Exclusive Ladies Hand Bag | 100% Leather & Cotton Fabrics | Very High Quality",
    color: "Blue with Designer Fabrics",
    size: " H x W - 10' x 14' ",
  },

  {
    id: 6,
    productCode: "LTB-004",
    category: "bag",
    subCategory: "officeBag",
    price: 1790.0,
    img: "https://i.imgur.com/5oAGVeV.jpg",
    description:
      "Exclusive Ladies Hand Bag | 100% Leather & Cotton Fabrics | Very High Quality ",
    color: "Black with Designer Fabrics",
    size: " H x W - 10' x 14' ",
  },
  {
    id: 7,
    productCode: "FSB-002",
    category: "bag",
    subCategory: "officeBag",
    price: 1000.0,
    img: "https://i.imgur.com/biQVbzw.jpg",
    description:
      "Exclusive Ladies Hand Bag | 100% Leather & Cotton Fabrics | Very High Quality",
    color: "Blue Color Leather with Designer Fabrics",
    size: " H x W - 15' x 16' ",
  },
  {
    id: 8,
    productCode: "LCB-0002",
    category: "bag",
    subCategory: "officeBag",
    price: 1650.0,
    img: "https://i.imgur.com/ZfJHNBe.jpg",
    description:
      "Exclusive Ladies Hand Bag | 100% Leather & Cotton Fabrics | Very High Quality",
    color: "Red Wine with Black Color Leather",
    size: " H x W - 12.5' x 9.5' ",
  },
  {
    id: 9,
    productCode: "PB-006",
    category: "bag",
    subCategory: "officeBag",
    price: 1390.0,
    img: "https://i.imgur.com/Zd7bZ5K.jpg",
    description: "Exclusive Ladies Hand Bag | 100% Leather | Very High Quality",
    color: "Black",
    size: " H x W x L - 13.5'x13'x5' ",
  },
  {
    id: 10,
    productCode: "PB-006",
    category: "bag",
    subCategory: "officeBag",
    price: 1390.0,
    img: "https://i.imgur.com/iLVUluq.jpg",
    description: "Exclusive Ladies Hand Bag | 100% Leather | Very High Quality",
    color: "red",
    size: " H x W x L - 13.5'x13'x5' ",
  },
  {
    id: 11,
    productCode: "PB-006",
    category: "bag",
    subCategory: "officeBag",
    price: 1390.0,
    img: "https://i.imgur.com/TiyhKHa.jpg",
    description: "Exclusive Ladies Hand Bag | 100% Leather | Very High Quality",
    color: "purple",
    size: " H x W x L - 13.5'x13'x5' ",
  },
  {
    id: 12,
    productCode: "PB-006",
    category: "bag",
    subCategory: "officeBag",
    price: 1390.0,
    img: "https://i.imgur.com/PJ7Y4t1.jpg",
    description: "Exclusive Ladies Hand Bag | 100% Leather | Very High Quality",
    color: "Olive",
    size: " H x W x L - 13.5'x13'x5' ",
  },
  {
    id: 13,
    productCode: "YCB-602",
    category: "bag",
    subCategory: "officeBag",
    price: 1200.0,
    img: "https://i.imgur.com/pxbGo05.jpg",
    description:
      "Exclusive Ladies Party Bag | 100% Leather | Very High Quality",
    color: "Snow Drift",
    size: " H x W x L - 7' x 8' x 4' ",
  },
  {
    id: 14,
    productCode: "RBG-102",
    category: "bag",
    subCategory: "officeBag",
    price: 1150.0,
    img: "https://i.imgur.com/7ZKsikz.jpg",
    description:
      "Exclusive Ladies Hand Bag | 100% Leather & Makhmal Fabrics | Very High Quality",
    color: "Blue with Red",
    size: " H x W - 10' x 14' ",
  },
  {
    id: 15,
    productCode: "RBG-102",
    category: "bag",
    subCategory: "officeBag",
    price: 1150.0,
    img: "https://i.imgur.com/YKcPRxY.jpg",
    description: "Exclusive Ladies Hand Bag | 100% Leather | Very High Quality",
    color: "Black with Brown",
    size: " H x W - 10' x 14' ",
  },
  {
    id: 16,
    productCode: "RBG-102",
    category: "bag",
    subCategory: "officeBag",
    price: 1150.0,
    img: "https://i.imgur.com/698eOa6.jpg",
    description:
      "Exclusive Ladies Hand Bag | 100% Leather | Very High Quality ",
    color: "red with silver",
    size: " H x W - 10' x 14' ",
  },
  {
    id: 17,
    productCode: "RBG-102",
    category: "bag",
    subCategory: "officeBag",
    price: 1800.0,
    img: "https://i.imgur.com/Y4N3JE2.png",
    description:
      "Exclusive Ladies Party Bag | 100% Leather | Very High Quality ",
    color: "Blue",
    size: " L x W x H - 9' x 9.5' x 2.5' ",
  },
  {
    id: 18,
    productCode: "RBG-102",
    category: "bag",
    subCategory: "officeBag",
    price: 1800.0,
    img: "https://i.imgur.com/CdA7NIp.png",
    description:
      "Exclusive Ladies Party Bag | 100% Leather | Very High Quality ",
    color: "Off white",
    size: " L x W x H - 9' x 9.5' x 2.5' ",
  },
  {
    id: 19,
    productCode: "RBG-102",
    category: "bag",
    subCategory: "officeBag",
    price: 1800.0,
    img: "https://i.imgur.com/SOqUdkg.png",
    description:
      "Exclusive Ladies Party Bag | 100% Leather | Very High Quality ",
    color: "Black",
    size: " L x W x H - 9' x 9.5' x 2.5' ",
  },
  {
    id: 20,
    productCode: "RBG-102",
    category: "bag",
    subCategory: "officeBag",
    price: 2000.0,
    img: "https://i.imgur.com/uQcOT1O.png",
    description:
      "Exclusive Ladies Party Bag | 100% Leather | Very High Quality ",
    color: "Pink",
    size: " L x W x H - 9' x 9' x 3' ",
  },
  {
    id: 21,
    productCode: "RBG-102",
    category: "bag",
    subCategory: "officeBag",
    price: 2000.0,
    img: "https://i.imgur.com/y95MSuv.png",
    description:
      "Exclusive Ladies Party Bag | 100% Leather | Very High Quality ",
    color: "Off White",
    size: " L x W x H - 9' x 9' x 3' ",
  },
  {
    id: 22,
    productCode: "RBG-102",
    category: "bag",
    subCategory: "officeBag",
    price: 2000.0,
    img: "https://i.imgur.com/5wwd2iP.png",
    description:
      "Exclusive Ladies Party Bag | 100% Leather | Very High Quality ",
    color: "Black",
    size: " L x W x H - 9' x 9' x 3' ",
  },
  {
    id: 23,
    productCode: "RBG-102",
    category: "bag",
    subCategory: "officeBag",
    price: 2000.0,
    img: "https://i.imgur.com/4QFmd3M.png",
    description:
      "Exclusive Ladies Party Bag | 100% Leather | Very High Quality ",
    color: "Dark white",
    size: " L x W x H - 9' x 9' x 3' ",
  },
  {
    id: 24,
    productCode: "RBG-102",
    category: "bag",
    subCategory: "officeBag",
    price: 2000.0,
    img: "https://i.imgur.com/q0Nbpjp.png",
    description:
      "Exclusive Ladies Party Bag | 100% Leather | Very High Quality ",
    color: "red black mixed",
    size: " L x W x H - 9' x 9' x 3' ",
  },
  {
    id: 25,
    productCode: "RBG-102",
    category: "bag",
    subCategory: "officeBag",
    price: 2000.0,
    img: "https://i.imgur.com/svJHONz.png",
    description:
      "Exclusive Ladies Party Bag | 100% Leather | Very High Quality ",
    color: "Black red mixed",
    size: " L x W x H - 9' x 9' x 3' ",
  },
  {
    id: 26,
    productCode: "LFR 001",
    category: "bag",
    subCategory: "officeBag",
    price: 1550.0,
    img: "https://i.imgur.com/gSfLCo4.jpg",
    description:
      "Exclusive Ladies Party Bag | 100% Leather | Very High Quality ",
    color: "Blue with Designer Fabrics",
    size: " H x W - 10' x 14' ",
  },
  {
    id: 27,
    productCode: "LFR 001",
    category: "bag",
    subCategory: "officeBag",
    price: 1550.0,
    img: "https://i.imgur.com/EhBvt7V.jpg",
    description:
      "Exclusive Ladies Party Bag | 100% Leather | Very High Quality ",
    color: "Olive grey Designer Fabrics",
    size: " H x W - 10' x 14' ",
  },
];

//this is gym bag
export const gymBag = [
  {
    id: 4,
    ProductCode: "BBG-7030",
    img: "https://i.imgur.com/p0OIse7.jpg",
    price: 2700,
  },
  {
    id: 5,
    ProductCode: "BBG-703",
    img: "https://i.imgur.com/5ewviKd.jpg",
    price: 2700,
  },
  {
    id: 6,
    ProductCode: "BGB-6003",
    img: "https://i.imgur.com/Nr4CATv.jpg",
    price: 2700,
  },
];

//this is office bag
export const officeBag = [
  {
    id: 7,
    ProductCode: "BBG-7030",
    img: "https://i.imgur.com/baKnYHC.jpg",
    price: 2700,
  },
  {
    id: 8,
    ProductCode: "BBG-703",
    img: "https://i.imgur.com/0iCj7UJ.jpg",
    price: 2700,
  },
  {
    id: 9,
    ProductCode: "BGB-6003",
    img: "https://i.imgur.com/TD8aBbi.png",
    price: 2700,
  },
];
// this is laptop bag
export const laptopBag = [
  {
    id: 1,
    productCode: "BGB-6003",
    category: "bag",
    subCategory: "officeBag",
    price: 2700.0,
    img: "https://i.imgur.com/tqdTRIv.jpg",
    description:
      "Exclusive Laptop Bag | 100% Leather & Cotton Fabrics | Very High Quality | Small Handle : 13' Round | Outer Chain : 8'5 ",
    color: "Red Wine with Blue Leather",
    size: "  H x W x L - 13.5'x13'x5' ",
  },
  {
    id: 2,
    productCode: "BGB-6002",
    category: "bag",
    subCategory: "officeBag",
    price: 2700.0,
    img: "https://i.imgur.com/f50G9LK.jpg",
    description:
      "Exclusive Ladies Laptop Bag | 100% Leather | Very High Quality | Small Handle : 13' Round | Outer Chain : 8'5 ",
    color: "Black Color Leather",
    size: " H x W x L - 13.5'x13'x5' ",
  },
  {
    id: 11,
    ProductCode: "BBG-703",
    img: "https://i.imgur.com/0iCj7UJ.jpg",
    price: 2700,
  },
  {
    id: 12,
    ProductCode: "BGB-6003",
    img: "https://i.imgur.com/baKnYHC.jpg",
    price: 2700,
  },
];
