// this is ladis Bag
export const womenBag = [
  {
    id: 1,
    ProductCode: "FSB-002",
    category: "bag",
    subCategory: "officeBag",
    price: 1000.0,
    img: "https://i.ibb.co/TP9PN3h/FSB-002.webp",
    description:
      "Exclusive Ladies Hand Bag | 100% Leather & Cotton Fabrics | Very High Quality",
    color: "Blue Color Leather with Designer Fabrics",
    size: " H x W - 15' x 16' ",
  },
  {
    id: 2,
    ProductCode: "LCB-0002J",
    category: "bag",
    subCategory: "officeBag",
    price: 1800.0,
    img: "https://i.ibb.co/HXKSQD1/LCB-0002-J.webp",
    description:
      "Exclusive Ladies Hand Bag | 100% Leather & Cotton Fabrics | Very High Quality",
    color: "Brown Designer Leather with Black Color Leather",
    size: "  H x W - 12.5' x 9.5' ",
  },
  {
    id: 3,
    ProductCode: "BBG-7030",
    category: "bag",
    subCategory: "officeBag",
    price: 2700.0,
    img: "https://i.ibb.co/HV2YZ6W/BBG-7030.webp",
    description:
      "Exclusive Ladies Hand Bag | 100% Leather & Cotton Fabrics | Very High Quality",
    color: "Red Wine with Blue Leather",
    size: "  H x W x L - 10' x 14' x 5' ",
  },
  {
    id: 4,
    ProductCode: "VCB-603",
    category: "bag",
    subCategory: "officeBag",
    price: 1200.0,
    img: "https://i.ibb.co/273QFPC/VCB-603.webp",
    description:
      "Exclusive Ladies Party Bag | 100% Leather & Cotton Fabrics | Very High Quality",
    color: "red",
    size: " H x W x L - 7' x 8' x 4' ",
  },
  {
    id: 5,
    ProductCode: "LTB-005",
    category: "bag",
    subCategory: "officeBag",
    price: 1790.0,
    img: "https://i.ibb.co/P44JCmr/LTB-005.webp",
    description:
      "Exclusive Ladies Hand Bag | 100% Leather & Cotton Fabrics | Very High Quality",
    color: "Blue with Designer Fabrics",
    size: " H x W - 10' x 14' ",
  },

  {
    id: 6,
    ProductCode: "LTB-004",
    category: "bag",
    subCategory: "officeBag",
    price: 1790.0,
    img: "https://i.ibb.co/pXntMY9/LTB-004.webp",
    description:
      "Exclusive Ladies Hand Bag | 100% Leather & Cotton Fabrics | Very High Quality ",
    color: "Black with Designer Fabrics",
    size: " H x W - 10' x 14' ",
  },
  {
    id: 7,
    ProductCode: "FSB-003",
    category: "bag",
    subCategory: "officeBag",
    price: 1000.0,
    img: "https://i.ibb.co/Z1zJRJD/FSB-003.webp",
    description:
      "Exclusive Ladies Hand Bag | 100% Leather & Cotton Fabrics | Very High Quality",
    color: "Blue Color Leather with Designer Fabrics",
    size: " H x W - 15' x 16' ",
  },
  {
    id: 8,
    ProductCode: "LCB-0002",
    category: "bag",
    subCategory: "officeBag",
    price: 1650.0,
    img: "https://i.ibb.co/RjMrxcY/LCB-0002.webp",
    description:
      "Exclusive Ladies Hand Bag | 100% Leather & Cotton Fabrics | Very High Quality",
    color: "Red Wine with Black Color Leather",
    size: " H x W - 12.5' x 9.5' ",
  },
  {
    id: 9,
    ProductCode: "PB-006",
    category: "bag",
    subCategory: "officeBag",
    price: 1390.0,
    img: "https://i.ibb.co/q7Vm2SH/PB-006.webp",
    description: "Exclusive Ladies Hand Bag | 100% Leather | Very High Quality",
    color: "Black",
    size: " H x W x L - 13.5'x13'x5' ",
  },
  {
    id: 10,
    ProductCode: "PB-007",
    category: "bag",
    subCategory: "officeBag",
    price: 1390.0,
    img: "https://i.ibb.co/tmzqSGX/PB-007.webp",
    description: "Exclusive Ladies Hand Bag | 100% Leather | Very High Quality",
    color: "red",
    size: " H x W x L - 13.5'x13'x5' ",
  },
  {
    id: 11,
    ProductCode: "PB-008",
    category: "bag",
    subCategory: "officeBag",
    price: 1390.0,
    img: "https://i.ibb.co/zSbpnXC/PB-008.webp",
    description: "Exclusive Ladies Hand Bag | 100% Leather | Very High Quality",
    color: "Olive",
    size: " H x W x L - 13.5'x13'x5' ",
  },
  {
    id: 12,
    ProductCode: "PB-009",
    category: "bag",
    subCategory: "officeBag",
    price: 1390.0,
    img: "https://i.ibb.co/JQY85Wb/PB-009.webp",
    description: "Exclusive Ladies Hand Bag | 100% Leather | Very High Quality",
    color: "purple",
    size: " H x W x L - 13.5'x13'x5' ",
  },
  {
    id: 13,
    ProductCode: "YCB-602",
    category: "bag",
    subCategory: "officeBag",
    price: 1200.0,
    img: "https://i.ibb.co/Zftg07H/YCB-602.webp",
    description:
      "Exclusive Ladies Party Bag | 100% Leather | Very High Quality",
    color: "Snow Drift",
    size: " H x W x L - 7' x 8' x 4' ",
  },
  {
    id: 14,
    ProductCode: "RBG-102",
    category: "bag",
    subCategory: "officeBag",
    price: 1150.0,
    img: "https://i.ibb.co/wdnM3zR/RBG-102.webp",
    description:
      "Exclusive Ladies Hand Bag | 100% Leather & Makhmal Fabrics | Very High Quality",
    color: "Blue with Red",
    size: " H x W - 10' x 14' ",
  },
  {
    id: 15,
    ProductCode: "RBG-103",
    category: "bag",
    subCategory: "officeBag",
    price: 1150.0,
    img: "https://i.ibb.co/hF6Kxkw/RBG-103.webp",
    description: "Exclusive Ladies Hand Bag | 100% Leather | Very High Quality",
    color: "Black with Brown",
    size: " H x W - 10' x 14' ",
  },
  {
    id: 16,
    ProductCode: "RBG-104",
    category: "bag",
    subCategory: "officeBag",
    price: 1150.0,
    img: "https://i.ibb.co/16pZnw1/RBG-104.webp",
    description:
      "Exclusive Ladies Hand Bag | 100% Leather | Very High Quality ",
    color: "red with silver",
    size: " H x W - 10' x 14' ",
  },
  {
    id: 17,
    ProductCode: "RBG-105",
    category: "bag",
    subCategory: "officeBag",
    price: 1800.0,
    img: "https://i.ibb.co/8KpnTKh/RBG-105.webp",
    description:
      "Exclusive Ladies Party Bag | 100% Leather | Very High Quality ",
    color: "Blue",
    size: " L x W x H - 9' x 9.5' x 2.5' ",
  },
  {
    id: 18,
    ProductCode: "RBG-106",
    category: "bag",
    subCategory: "officeBag",
    price: 1800.0,
    img: "https://i.ibb.co/Bt7NZf7/RBG-106.webp",
    description:
      "Exclusive Ladies Party Bag | 100% Leather | Very High Quality ",
    color: "Off white",
    size: " L x W x H - 9' x 9.5' x 2.5' ",
  },
  {
    id: 19,
    ProductCode: "RBG-107",
    category: "bag",
    subCategory: "officeBag",
    price: 1800.0,
    img: "https://i.ibb.co/Pxc4r3v/RBG-107.webp",
    description:
      "Exclusive Ladies Party Bag | 100% Leather | Very High Quality ",
    color: "Black",
    size: " L x W x H - 9' x 9.5' x 2.5' ",
  },
  {
    id: 20,
    ProductCode: "RBG-108",
    category: "bag",
    subCategory: "officeBag",
    price: 2000.0,
    img: "https://i.ibb.co/qgHRh3s/RBG-108.webp",
    description:
      "Exclusive Ladies Party Bag | 100% Leather | Very High Quality ",
    color: "Pink",
    size: " L x W x H - 9' x 9' x 3' ",
  },
  {
    id: 21,
    ProductCode: "RBG-109",
    category: "bag",
    subCategory: "officeBag",
    price: 2000.0,
    img: "https://i.ibb.co/kXtLCt2/RBG-109.webp",
    description:
      "Exclusive Ladies Party Bag | 100% Leather | Very High Quality ",
    color: "Off White",
    size: " L x W x H - 9' x 9' x 3' ",
  },
  {
    id: 22,
    ProductCode: "RBG-110",
    category: "bag",
    subCategory: "officeBag",
    price: 2000.0,
    img: "https://i.ibb.co/B2TQNyd/RBG-110.webp",
    description:
      "Exclusive Ladies Party Bag | 100% Leather | Very High Quality ",
    color: "Black",
    size: " L x W x H - 9' x 9' x 3' ",
  },
  {
    id: 23,
    ProductCode: "RBG-111",
    category: "bag",
    subCategory: "officeBag",
    price: 2000.0,
    img: "https://i.ibb.co/9tsBJm7/RBG-111.webp",
    description:
      "Exclusive Ladies Party Bag | 100% Leather | Very High Quality ",
    color: "Dark white",
    size: " L x W x H - 9' x 9' x 3' ",
  },
  {
    id: 24,
    ProductCode: "RBG-112",
    category: "bag",
    subCategory: "officeBag",
    price: 2000.0,
    img: "https://i.ibb.co/KyjnWT6/RBG-112.webp",
    description:
      "Exclusive Ladies Party Bag | 100% Leather | Very High Quality ",
    color: "red black mixed",
    size: " L x W x H - 9' x 9' x 3' ",
  },
  {
    id: 25,
    ProductCode: "RBG-113",
    category: "bag",
    subCategory: "officeBag",
    price: 2000.0,
    img: "https://i.ibb.co/5FqfJtC/RBG-113.webp",
    description:
      "Exclusive Ladies Party Bag | 100% Leather | Very High Quality ",
    color: "Black red mixed",
    size: " L x W x H - 9' x 9' x 3' ",
  },
  {
    id: 26,
    ProductCode: "LFR-001",
    category: "bag",
    subCategory: "officeBag",
    price: 1550.0,
    img: "https://i.ibb.co/RjwBS1j/LFR-001.webp",
    description:
      "Exclusive Ladies Party Bag | 100% Leather | Very High Quality ",
    color: "Olive grey Designer Fabrics",
    size: " H x W - 10' x 14' ",
  },
  {
    id: 27,
    ProductCode: "LFR-002",
    category: "bag",
    subCategory: "officeBag",
    price: 1550.0,
    img: "https://i.ibb.co/qkqZHdw/LFR-002.webp",
    description:
      "Exclusive Ladies Party Bag | 100% Leather | Very High Quality ",
    color: "Blue with Designer Fabrics",
    size: " H x W - 10' x 14' ",
  },
];

//this is gym bag
export const gymBag = [
  {
    id: 1,
    ProductCode: "BGG-8001",
    img: "https://i.ibb.co/SBsmy5R/BGG-8001.webp",
    price: 1600.0,
    description:
      "Exclusive Multipurpose Travel or Gym Bag | 100% Leather with High Quality Synthetic Fabrics | Very High Quality",
    color: "Red Leather with Maroon Fabrics",
    size: " H x W - 14' x 18' ",
  },

  {
    id: 2,
    ProductCode: "BGG-8002",
    img: "https://i.ibb.co/59q8MgZ/BGG-8002.webp",
    price: 1600.0,
    description:
      "Exclusive Multipurpose Travel or Gym Bag | 100% Leather with High Quality Synthetic Fabrics | Very High Quality",
    color: "Green Leather with Black Fabrics",
    size: " H x W - 14' x 18' ",
  },
];

//this is office bag
export const officeBag = [
  {
    id: 1,
    ProductCode: "BLB-605",
    img: "https://i.ibb.co/xS49PKR/BLB-605.webp",
    price: 5500.0,
    description:
      "Exclusive Multipurpose Office cum Laptop Bag | 100% Leather | Very High Quality",
    color: "Black Leather",
    size: " H x W x L - 14' x 17.5' x 4' ",
  },
  {
    id: 2,
    ProductCode: "BLB-607",
    img: "https://i.ibb.co/Tg5qvn9/BLB-607.webp",
    price: 5500.0,
    description:
      "Exclusive Multipurpose Office cum Laptop Bag | 100% Leather | Very High Quality",
    color: "Black Leather",
    size: " H x W x L - 17' x 10.5' x 6' ",
  },
  {
    id: 3,
    ProductCode: "CRB-01",
    img: "https://i.ibb.co/GcFcJPp/CRB-01.webp",
    price: 1200.0,
    description:
      "Exclusive Multipurpose Office cum Laptop Bag | 100% Leather | Very High Quality",
    color: "Black Leather",
    size: "  H x W x L - 8' x 5' x2 ' ",
  },
  {
    id: 4,
    ProductCode: "BLB-606",
    img: "https://i.ibb.co/pZtW4gJ/BLB-606.webp",
    price: 5200.0,
    description:
      "Exclusive Multipurpose Office cum Laptop Bag | 100% Leather | Very High Quality",
    color: "Black Leather",
    size: " H x W x L - 17' x 10.5' x 6' ",
  },
  {
    id: 5,
    ProductCode: "LPB-001",
    img: "https://i.ibb.co/DGHJbwy/LPB-001.webp",
    price: 2050.0,
    description:
      "Exclusive Multipurpose Office cum Laptop Bag | 100% Leather | Very High Quality",
    color: "Dark Brown",
    size: "  H x W x L - 12.5' x 10.5' x 4.5 ' ",
  },
  {
    id: 6,
    ProductCode: "LPB-002",
    img: "https://i.ibb.co/vD9v1b7/LPB-002.webp",
    price: 2050.0,
    description:
      "Exclusive Multipurpose Office cum Laptop Bag | 100% Leather | Very High Quality",
    color: "Medium Dark Brown",
    size: "  H x W x L - 12.5' x 10.5' x 4.5 ' ",
  },
  {
    id: 7,
    ProductCode: "CRB-02",
    img: "https://i.ibb.co/9bYxY7M/CRB-02.webp",
    price: 1200.0,
    description:
      "2 Part Multipurpose Bag | 100% Leather | In this pocket you can carry Mobile, Notepad & other essential goods.",
    color: "Silver",
    size: "  H x W x L - 8' x 5' x2 ' ",
  },
  {
    id: 8,
    ProductCode: "LPB-0010",
    img: "https://i.ibb.co/ydB9g8M/LPB-0010.webp",
    price: 2700.0,
    description:
      "1 Part Multipurpose Backpack | 100% Leather | In this pocket you can carry Mobile, Notepad & other essential goods.",
    color: "Black with Maroon",
    size: "  H x W x L - 14' x 10' x 6' ",
  },
  {
    id: 9,
    ProductCode: "CAN-01",
    img: "https://i.ibb.co/DCVgB3R/CAN-01.webp",
    price: 1950.0,
    description: "Exclusive Multipurpose Office CANVAS Backpack | 100% Leather",
    color: "Black Canvas & Leather",
    size: "  H x W x D - 18' x 12' x 6' ",
  },
  {
    id: 10,
    ProductCode: "LPS-001",
    img: "https://i.ibb.co/yV0vQms/LPS-001.webp",
    price: 1500.0,
    description:
      "Exclusive Multipurpose Office MiNi Backpack | 100% Leather | In this pocket you can carry Mobile, Notepad & makeup notebook and other essential goods",
    color: "Black Canvas & Leather",
    size: "  H x W x L - 10' x 6' x1.5' ",
  },
];
// this is laptop bag
export const laptopBag = [
  {
    id: 1,
    ProductCode: "BGB-6003",
    category: "bag",
    subCategory: "officeBag",
    price: 2700.0,
    img: "https://i.ibb.co/mTL5MrW/BGB-6003.webp",
    description:
      "Exclusive Laptop Bag | 100% Leather & Cotton Fabrics | Very High Quality | Small Handle : 13' Round | Outer Chain : 8'5 ",
    color: "Red Wine with Blue Leather",
    size: "  H x W x L - 13.5'x13'x5' ",
  },
  {
    id: 2,
    ProductCode: "BGB-6002",
    category: "bag",
    subCategory: "officeBag",
    price: 2700.0,
    img: "https://i.ibb.co/Prw4kg4/BGB-6002.webp",
    description:
      "Exclusive Ladies Laptop Bag | 100% Leather | Very High Quality | Small Handle : 13' Round | Outer Chain : 8'5 ",
    color: "Black Color Leather",
    size: " H x W x L - 13.5'x13'x5' ",
  },
  {
    id: 3,
    ProductCode: "BLB-605",
    img: "https://i.ibb.co/xS49PKR/BLB-605.webp",
    price: 5500.0,
    description:
      "Exclusive Multipurpose Office cum Laptop Bag | 100% Leather | Very High Quality",
    color: "Black Leather",
    size: " H x W x L - 14' x 17.5' x 4' ",
  },
  {
    id: 4,
    ProductCode: "BLB-607",
    img: "https://i.ibb.co/Tg5qvn9/BLB-607.webp",
    price: 5500.0,
    description:
      "Exclusive Multipurpose Office cum Laptop Bag | 100% Leather | Very High Quality",
    color: "Black Leather",
    size: " H x W x L - 17' x 10.5' x 6' ",
  },
  {
    id: 5,
    ProductCode: "CRB-01",
    img: "https://i.ibb.co/GcFcJPp/CRB-01.webp",
    price: 1200.0,
    description:
      "Exclusive Multipurpose Office cum Laptop Bag | 100% Leather | Very High Quality",
    color: "Black Leather",
    size: "  H x W x L - 8' x 5' x2 ' ",
  },
  {
    id: 6,
    ProductCode: "BLB-606",
    img: "https://i.ibb.co/pZtW4gJ/BLB-606.webp",
    price: 5200.0,
    description:
      "Exclusive Multipurpose Office cum Laptop Bag | 100% Leather | Very High Quality",
    color: "Black Leather",
    size: "  H x W x L - 14' x 17.5' x 4' ",
  },
  {
    id: 7,
    ProductCode: "LPB-001",
    img: "https://i.ibb.co/DGHJbwy/LPB-001.webp",
    price: 2050.0,
    description:
      "Exclusive Multipurpose Office cum Laptop Bag | 100% Leather | Very High Quality",
    color: "Dark Brown",
    size: "  H x W x L - 12.5' x 10.5' x 4.5 ' ",
  },
  {
    id: 8,
    ProductCode: "LPB-002",
    img: "https://i.ibb.co/vD9v1b7/LPB-002.webp",
    price: 2050.0,
    description:
      "Exclusive Multipurpose Office cum Laptop Bag | 100% Leather | Very High Quality",
    color: "Medium Dark Brown",
    size: "  H x W x L - 12.5' x 10.5' x 4.5 ' ",
  },
  {
    id: 9,
    ProductCode: "LPS-003",
    category: "bag",
    price: 2500.0,
    img: "https://i.ibb.co/yV0vQms/LPS-001.webp",
    description:
      "Exclusive Multipurpose BackPack and laptop cover | 100% Leather | Very High Quality",
    color: "Black",
    size: " H x W x L - 16' x 11' x1.5' ",
  },
  {
    id: 10,
    ProductCode: "LPS-002",
    category: "bag",
    price: 2200.0,
    img: "https://i.ibb.co/fXDLyzb/LPS-002.webp",
    description:
      "Exclusive Multipurpose BackPack and laptop cover | 100% Leather | Very High Quality",
    color: "Black",
    size: " H x W x L - 15' x 11' x1.5' ",
  },
];
