// this is ladies bag
export const womenBelt = [
  {
    id: 1,
    ProductCode: "ELBJ-7001",
    img: "https://i.ibb.co/xD18d1Y/ELBJ-7001.webp",
    price: 600.0,
    description: "Exclusive Ladies Leather Belt | Very High Quality",
    color: "Red Leather",
  },
  {
    id: 2,
    ProductCode: "ELBJ-7002",
    img: "https://i.ibb.co/RygN3y3/ELBJ-7002.webp",
    price: 600.0,
    description: "Exclusive Ladies Leather Belt | Very High Quality",
    color: "Black Leather",
  },
  {
    id: 3,
    ProductCode: "ELBJ-7007",
    img: "https://i.ibb.co/j6hg3tY/ELBJ-7007.webp",
    price: 700.0,
    description: "Exclusive Ladies Leather Belt | Very High Quality",
    color: "Green Leather",
  },
  {
    id: 4,
    ProductCode: "ELBJ-7008",
    img: "https://i.ibb.co/NpwGVj1/ELBJ-7008.webp",
    price: 700.0,
    description: "Exclusive Ladies Leather Belt | Very High Quality",
    color: "Yellow Leather",
  },
  {
    id: 5,
    ProductCode: "ELBJ-7009",
    img: "https://i.ibb.co/jkRFkLv/ELBJ-7009.webp",
    price: 600.0,
    description: "Exclusive Ladies Leather Belt | Very High Quality",
    color: "Purple Leather",
  },
  {
    id: 6,
    ProductCode: "LBE-701 (Yellow)",
    img: "https://i.ibb.co/zZ5v52x/LBE-701-Yellow.webp",
    price: 600.0,
    description: "Exclusive Ladies Leather Belt | Very High Quality",
    color: "Yellow Leather",
  },
  {
    id: 7,
    ProductCode: "LBJ-703",
    img: "https://i.ibb.co/GtRGMh9/LBJ-703.webp",
    price: 600.0,
    description: "Exclusive Ladies Leather Belt | Very High Quality",
    color: "Black Leather",
  },
  {
    id: 8,
    ProductCode: "ELBJ-7007(Blue)",
    img: "https://i.ibb.co/ZXBkx11/ELBJ-7007-Blue.webp",
    price: 600.0,
    description: "Exclusive Ladies Leather Belt | Very High Quality",
    color: "Blue Leather",
  },
  {
    id: 9,
    ProductCode: "LBJ-704",
    img: "https://i.ibb.co/WyhFpyB/LBJ-704.webp",
    price: 525.0,
    description: "Exclusive Ladies Leather Belt | Very High Quality",
    color: "Green Leather",
  },
];

// this is gents belt
export const menBelt = [
  {
    id: 1,
    ProductCode: "BCS-700",
    img: "https://i.ibb.co/c1fsvNY/BCS-700.webp",
    price: 700.0,
    description: "Exclusive Gent's Leather Belt | Very High Quality",
    color: "Chocolate & Black Leather",
  },
  {
    id: 2,
    ProductCode: "BMB-1112",
    img: "https://i.ibb.co/Tq799V0/BMB-1112.webp",
    price: 650.0,
    description: "Exclusive Gent's Leather Belt | Very High Quality",
    color: "Black Leather",
  },
  {
    id: 3,
    ProductCode: "BCSB-601",
    img: "https://i.ibb.co/pbK0NwS/BCSB-601.webp",
    price: 700.0,
    description: "Exclusive Gent's Leather Belt | Very High Quality",
    color: "Dark Brown & Light Brown Leather",
  },
  {
    id: 4,
    ProductCode: "CBMB-1111",
    img: "https://i.ibb.co/xLh4ktM/CBMB-1111.webp",
    price: 700.0,
    description: "Exclusive Gent's Leather Belt | Very High Quality",
    color: "Black & Chocolate Crocodile Printed Leather",
  },
  {
    id: 5,
    ProductCode: "HBB-1113",
    img: "https://i.ibb.co/KynxYpV/HBB-1113.webp",
    price: 750.0,
    description: "Exclusive Gent's Leather Belt | Very High Quality",
    color: "Chocolate & Light Brown Leather",
  },
  {
    id: 6,
    ProductCode: "HBB-2001",
    img: "https://i.ibb.co/jb0MgF1/HBB-2001.webp",
    price: 700.0,
    description: "Exclusive Gent's Leather Belt | Very High Quality",
    color: "Dark Brown & Light Brown Leather",
  },
  {
    id: 7,
    ProductCode: "MBS-800",
    img: "https://i.ibb.co/x13PvWh/MBS-800.webp",
    price: 750.0,
    description: "Exclusive Gent's Leather Belt | Very High Quality",
    color: "Chocolate & Light Brown Leather",
  },
];
