// this is ladies bag
export const womenBelt = [
  {
    id: 1,
    ProductCode: "ELBJ-7001",
    img: "https://i.imgur.com/w6NWQor.jpg",
    price: 600.0,
    description: "Exclusive Ladies Leather Belt | Very High Quality",
    color: "Red Leather",
  },
  {
    id: 2,
    ProductCode: "ELBJ-7001",
    img: "https://i.imgur.com/qN3AbvB.png",
    price: 600.0,
    description: "Exclusive Ladies Leather Belt | Very High Quality",
    color: "Black Leather",
  },
  {
    id: 3,
    ProductCode: "ELBJ-7005",
    img: "https://i.imgur.com/Cs6NTJZ.jpg",
    price: 700.0,
    description: "Exclusive Ladies Leather Belt | Very High Quality",
    color: "Green Leather",
  },
  {
    id: 4,
    ProductCode: "ELBJ-7007",
    img: "https://i.imgur.com/95kyWCo.jpg",
    price: 700.0,
    description: "Exclusive Ladies Leather Belt | Very High Quality",
    color: "Yellow Leather",
  },
  {
    id: 5,
    ProductCode: "ELBJ-7007",
    img: "https://i.imgur.com/nX5k6kQ.jpg",
    price: 600.0,
    description: "Exclusive Ladies Leather Belt | Very High Quality",
    color: "Yellow Leather",
  },
  {
    id: 6,
    ProductCode: "LBE-701 (Yellow)",
    img: "https://i.imgur.com/etNOA0S.jpg",
    price: 600.0,
    description: "Exclusive Ladies Leather Belt | Very High Quality",
    color: "Yellow Leather",
  },
  {
    id: 7,
    ProductCode: "LBJ-703",
    img: "https://i.imgur.com/sbilSpj.png",
    price: 600.0,
    description: "Exclusive Ladies Leather Belt | Very High Quality",
    color: "Black Leather",
  },
  {
    id: 8,
    ProductCode: "ELBJ-7007(Blue)",
    img: "https://i.imgur.com/tsmod11.jpg",
    price: 600.0,
    description: "Exclusive Ladies Leather Belt | Very High Quality",
    color: "Blue Leather",
  },
  {
    id: 9,
    ProductCode: "LBJ-704",
    img: "https://i.imgur.com/h0HB5Rs.png",
    price: 525.0,
    description: "Exclusive Ladies Leather Belt | Very High Quality",
    color: "Green Leather",
  },
];

// this is gents belt
export const menBelt = [
  {
    id: 1,
    ProductCode: "BCS-700",
    img: "https://i.imgur.com/fKP0SjW.jpg",
    price: 700.0,
    description: "Exclusive Gent's Leather Belt | Very High Quality",
    color: "Chocolate & Black Leather",
  },
  {
    id: 2,
    ProductCode: "BMB-1112",
    img: "https://i.imgur.com/XR2K3xU.jpg",
    price: 650.0,
    description: "Exclusive Gent's Leather Belt | Very High Quality",
    color: "Black Leather",
  },
  {
    id: 3,
    ProductCode: "BCSB-601",
    img: "https://i.imgur.com/ROI4Pux.jpg",
    price: 700.0,
    description: "Exclusive Gent's Leather Belt | Very High Quality",
    color: "Dark Brown & Light Brown Leather",
  },
  {
    id: 4,
    ProductCode: "CBMB-1111",
    img: "https://i.imgur.com/aFLKqdb.jpg",
    price: 700.0,
    description: "Exclusive Gent's Leather Belt | Very High Quality",
    color: "Black & Chocolate Crocodile Printed Leather",
  },
  {
    id: 5,
    ProductCode: "HBB-1113",
    img: "https://i.imgur.com/Kz9WXra.jpg",
    price: 750.0,
    description: "Exclusive Gent's Leather Belt | Very High Quality",
    color: "Chocolate & Light Brown Leather",
  },
  {
    id: 6,
    ProductCode: "HBB-2001",
    img: "https://i.imgur.com/GECBxy6.jpg",
    price: 700.0,
    description: "Exclusive Gent's Leather Belt | Very High Quality",
    color: "Dark Brown & Light Brown Leather",
  },
  {
    id: 7,
    ProductCode: "MBS-800",
    img: "https://i.imgur.com/lT4gkT2.png",
    price: 750.0,
    description: "Exclusive Gent's Leather Belt | Very High Quality",
    color: "Chocolate & Light Brown Leather",
  },
];
