export const womenShoes = [
  {
    id: 1,
    ProductCode: "BLS-106",
    img: "https://i.imgur.com/wwlWWm6.jpg",
    price: 1350.0,
    description: "Exclusive Ladies Sandal Shoe | Artificial Leather",
    color: "Ash (Deep)",
    size: "36, 37, 38, 39, 40 & 41",
  },
  {
    id: 2,
    ProductCode: "BSS-105",
    img: "https://i.imgur.com/2qNDMbR.jpg",
    price: 1300.0,
    description: "Exclusive Ladies Sandal Shoe | Artificial Leather",
    color: "Coffee (Glossy)",
    size: "36, 37, 38, 39, 40 & 41",
  },
  {
    id: 3,
    ProductCode: "CSS-103",
    img: "https://i.imgur.com/1F9IHbu.jpg",
    price: 1500.0,
    description: "Exclusive Ladies Sandal Shoe | Artificial Leather",
    color: "Light Pink (Glossy)",
    size: "36, 37, 38, 39, 40 & 41",
  },
  {
    id: 4,
    ProductCode: "STB-101",
    img: "https://i.imgur.com/hi1sTGL.jpg",
    price: 1000.0,
    description: "Exclusive Ladies Sandal Shoe | Artificial Leather",
    color: "Light Ash(Glossy) & Black",
    size: "36, 37, 38, 39, 40 & 41",
  },
  {
    id: 5,
    ProductCode: "BLS-106",
    img: "https://i.imgur.com/BlduQbX.jpg",
    price: 1350.0,
    description: "Exclusive Ladies Sandal Shoe | Artificial Leather",
    color: "Ash (Glossy)",
    size: "36, 37, 38, 39, 40 & 41",
  },
  {
    id: 6,
    ProductCode: "BSS-104",
    img: "https://i.imgur.com/0pbQ2NP.jpg",
    price: 1200.0,
    description: "Exclusive Ladies Sandal Shoe | Artificial Leather",
    color: "Black (Glossy)",
    size: "36, 37, 38, 39, 40 & 41",
  },
  {
    id: 7,
    ProductCode: "CSS-103",
    img: "https://i.imgur.com/OoJTzXf.jpg",
    price: 1500.0,
    description: "Exclusive Ladies Sandal Shoe | Artificial Leather",
    color: "Light Pink (Glossy)",
    size: "36, 37, 38, 39, 40 & 41",
  },
  {
    id: 8,
    ProductCode: "SHL-102",
    img: "https://i.imgur.com/b4rPuyr.jpg",
    price: 900.0,
    description: "Exclusive Ladies Sandal Shoe | Artificial Leather",
    color: "Light Pink (Glossy) & Black",
    size: "36, 37, 38, 39, 40 & 41",
  },
  {
    id: 9,
    ProductCode: "FS-113",
    img: "https://i.imgur.com/Y8KrIgK.png",
    price: 1000.0,
    description: "Exclusive Ladies Sandal Shoe | Artificial Leather",
    color: "Light Pink (Glossy)",
    size: "36, 37, 38, 39, 40 & 41",
  },
  {
    id: 10,
    ProductCode: "FS-112",
    img: "https://i.imgur.com/dJolPTx.png",
    price: 900.0,
    description: "Exclusive Ladies Sandal Shoe | Artificial Leather",
    color: "Light Ash(Glossy) & Black",
    size: "36, 37, 38, 39, 40 & 41",
  },
  {
    id: 11,
    ProductCode: "FS-111",
    img: "https://i.imgur.com/YNeNMnD.png",
    price: 1000.0,
    description: "Exclusive Ladies Sandal Shoe | Artificial Leather",
    color: "Light Ash(Glossy)",
    size: "36, 37, 38, 39, 40 & 41",
  },
];

export const menShoes = [
  {
    id: 1,
    ProductCode: "JSB-405",
    img: "https://i.imgur.com/dnKqcTr.jpg",
    price: 1100.0,
    description: "Exclusive Leather Gent's Sandal | 100% Leather",
    size: "39, 40, 41 & 42",
    color: "Black",
  },
  {
    id: 2,
    ProductCode: "JSB-403",
    img: "https://i.imgur.com/Bf2A06S.jpg",
    price: 1950.0,
    description: "Exclusive Leather Gent's Shoes | 100% Leather",
    size: "39, 40, 41 & 42",
    color: "Golden",
  },
  {
    id: 3,
    ProductCode: "JSB-402",
    img: "https://i.imgur.com/Tfw7YOp.jpg",
    price: 1950.0,
    description: "Exclusive Leather Gent's Shoes | 100% Leather",
    size: "39, 40, 41 & 42",
    color: "Black",
  },
  {
    id: 4,
    ProductCode: "JSB-404",
    img: "https://i.imgur.com/xdEzmqM.jpg",
    price: 1550.0,
    description: "Exclusive Leather Gent's Shoes | 100% Leather",
    size: "39, 40, 41 & 42",
    color: "Black",
  },
  {
    id: 5,
    ProductCode: "JSB-401",
    img: "https://i.imgur.com/OrPFdfe.jpg",
    price: 800.0,
    description: "Exclusive Leather Gent's Sandal | 100% Leather",
    size: "39, 40, 41 & 42",
    color: "Black",
  },
];
