export const womenShoes = [
  {
    id: 1,
    ProductCode: "BLS-106",
    img: "https://i.ibb.co/DVSTLNW/BLS-106.webp",
    price: 1350.0,
    description: "Exclusive Ladies Sandal Shoe | Artificial Leather",
    color: "Ash (Deep)",
    size: "36, 37, 38, 39, 40 & 41",
  },
  {
    id: 2,
    ProductCode: "BSS-105",
    img: "https://i.ibb.co/jhjwdjD/BSS-105.webp",
    price: 1300.0,
    description: "Exclusive Ladies Sandal Shoe | Artificial Leather",
    color: "Coffee (Glossy)",
    size: "36, 37, 38, 39, 40 & 41",
  },
  {
    id: 3,
    ProductCode: "CSS-103",
    img: "https://i.ibb.co/ZV8R2Zr/CSS-103.webp",
    price: 1500.0,
    description: "Exclusive Ladies Sandal Shoe | Artificial Leather",
    color: "Light Pink (Glossy)",
    size: "36, 37, 38, 39, 40 & 41",
  },
  {
    id: 4,
    ProductCode: "STB-101",
    img: "https://i.ibb.co/GsLHfMW/STB-101.webp",
    price: 1000.0,
    description: "Exclusive Ladies Sandal Shoe | Artificial Leather",
    color: "Light Ash(Glossy) & Black",
    size: "36, 37, 38, 39, 40 & 41",
  },
  {
    id: 5,
    ProductCode: "BLS-107",
    img: "https://i.ibb.co/Zmcbcm8/BLS-107.webp",
    price: 1350.0,
    description: "Exclusive Ladies Sandal Shoe | Artificial Leather",
    color: "Ash (Glossy)",
    size: "36, 37, 38, 39, 40 & 41",
  },
  {
    id: 6,
    ProductCode: "BSS-104",
    img: "https://i.ibb.co/dgNyw43/BSS-104.webp",
    price: 1200.0,
    description: "Exclusive Ladies Sandal Shoe | Artificial Leather",
    color: "Black (Glossy)",
    size: "36, 37, 38, 39, 40 & 41",
  },
  {
    id: 8,
    ProductCode: "SHL-102",
    img: "https://i.ibb.co/jTF5F66/SHL-102.webp",
    price: 900.0,
    description: "Exclusive Ladies Sandal Shoe | Artificial Leather",
    color: "Light Pink (Glossy) & Black",
    size: "36, 37, 38, 39, 40 & 41",
  },
  {
    id: 9,
    ProductCode: "FS-113",
    img: "https://i.ibb.co/3CSTmDx/FS-113.webp",
    price: 1000.0,
    description: "Exclusive Ladies Sandal Shoe | Artificial Leather",
    color: "Light Pink (Glossy)",
    size: "36, 37, 38, 39, 40 & 41",
  },
  {
    id: 10,
    ProductCode: "FS-112",
    img: "https://i.ibb.co/d078VnN/FS-112.webp",
    price: 900.0,
    description: "Exclusive Ladies Sandal Shoe | Artificial Leather",
    color: "Light Ash(Glossy) & Black",
    size: "36, 37, 38, 39, 40 & 41",
  },
  {
    id: 11,
    ProductCode: "FS-111",
    img: "https://i.ibb.co/M59XJ6r/FS-111.webp",
    price: 1000.0,
    description: "Exclusive Ladies Sandal Shoe | Artificial Leather",
    color: "Light Ash(Glossy)",
    size: "36, 37, 38, 39, 40 & 41",
  },
];

export const menShoes = [
  {
    id: 1,
    ProductCode: "JSB-405",
    img: "https://i.ibb.co/x5pJ0dv/JSB-405.webp",
    price: 1100.0,
    description: "Exclusive Leather Gent's Sandal | 100% Leather",
    size: "39, 40, 41 & 42",
    color: "Black",
  },
  {
    id: 2,
    ProductCode: "JSB-403",
    img: "https://i.ibb.co/WgGJ5ws/JSB-403.webp",
    price: 1950.0,
    description: "Exclusive Leather Gent's Shoes | 100% Leather",
    size: "39, 40, 41 & 42",
    color: "Golden",
  },
  {
    id: 3,
    ProductCode: "JSB-402",
    img: "https://i.ibb.co/QmkZWCV/JSB-402.webp",
    price: 1950.0,
    description: "Exclusive Leather Gent's Shoes | 100% Leather",
    size: "39, 40, 41 & 42",
    color: "Black",
  },
  {
    id: 4,
    ProductCode: "JSB-404",
    img: "https://i.ibb.co/0s03qy3/JSB-404.webp",
    price: 1550.0,
    description: "Exclusive Leather Gent's Shoes | 100% Leather",
    size: "39, 40, 41 & 42",
    color: "Black",
  },
  {
    id: 5,
    ProductCode: "JSB-401",
    img: "https://i.ibb.co/HGzyhBk/JSB-401.webp",
    price: 800.0,
    description: "Exclusive Leather Gent's Sandal | 100% Leather",
    size: "39, 40, 41 & 42",
    color: "Black",
  },
];
