// this is ladies wallet
export const WalletBoth = [
  {
    id: 1,
    ProductCode: "LGW-102",
    img: "https://i.imgur.com/uKtV5Rf.jpg",
    price: 550.0,
    description: "Exclusive Leather Wallet | Very High Quality",
    color: "Brown & Black Crocodile Printed Leather",
  },
  {
    id: 2,
    ProductCode: "LW-901",
    img: "https://i.imgur.com/cDCWNJZ.jpg",
    price: 850.0,
    description: "Exclusive Leather Wallet | Very High Quality",
    color: "Brown Leather",
  },
  {
    id: 3,
    ProductCode: "LW-902",
    img: "https://i.imgur.com/6NZKN7i.jpg",
    price: 750.0,
    description: "Exclusive Leather Wallet | Very High Quality",
    color: "Brown Leather",
  },
  {
    id: 4,
    ProductCode: "LW-905",
    img: "https://i.imgur.com/6BMfa0S.jpg",
    price: 825.0,
    description: "Exclusive Leather Wallet | Very High Quality",
    color: "Coffee Leather",
  },
  {
    id: 5,
    ProductCode: "LW-903",
    img: "https://i.imgur.com/v0mzDwR.jpg",
    price: 825.0,
    description: "Exclusive Leather Wallet | Very High Quality",
    color: "Blue Leather",
  },
  {
    id: 6,
    ProductCode: "WL-01",
    img: "https://i.imgur.com/ADy6Lpe.jpg",
    price: 700.0,
    description: "Exclusive Leather Wallet | Very High Quality",
    color: "Brown Leather",
  },
  {
    id: 7,
    ProductCode: "SW-802",
    img: "https://i.imgur.com/ZyFGCgT.png",
    price: 700.0,
    description: "Exclusive Leather Wallet | Very High Quality",
    color: "Black Leather",
  },
  {
    id: 8,
    ProductCode: "LW-901",
    img: "https://i.imgur.com/1OlK0gy.png",
    price: 750.0,
    description: "Exclusive Leather Wallet | Very High Quality",
    color: "Black Leather",
  },
  {
    id: 9,
    ProductCode: "WL-01",
    img: "https://i.imgur.com/YhtzRe5.jpg",
    price: 700.0,
    description: "Exclusive Leather Wallet | Very High Quality",
    color: "Black Leather",
  },
  {
    id: 10,
    ProductCode: "PC-01",
    img: "https://i.imgur.com/tA3Puee.jpg",
    price: 300.0,
    description: "Exclusive Leather Wallet | Very High Quality",
    color: "Brown Leather",
  },
  {
    id: 11,
    ProductCode: "PC-01",
    img: "https://i.imgur.com/J6xNNtV.jpg",
    price: 280.0,
    description: "Exclusive Leather Wallet | Very High Quality",
    color: "Black Leather",
  },
  {
    id: 12,
    ProductCode: "LW-18",
    img: "https://i.imgur.com/hjDVpjC.jpg",
    price: 950.0,
    description:
      "Multiple Card Holders & One Long Pockets for Holding Money & Other Necessary Goods.",
    color: "Black Leather",
  },
  {
    id: 13,
    ProductCode: "LW-19",
    img: "https://i.imgur.com/vKx0zHT.jpg",
    price: 950.0,
    description:
      "Multiple Card Holders & One Long Pockets for Holding Money & Other Necessary Goods.",
    color: "Brown Leather",
  },
  {
    id: 14,
    ProductCode: "PR 001",
    img: "https://i.imgur.com/IdQ1P1Y.png",
    price: 1200.0,
    description:
      "Long Wallet with Multiple Card Holder & four Long Pockets for Holding Money, Mobile & Other Necessary Goods.",
    color: "Black Leather",
  },
  {
    id: 15,
    ProductCode: "LW-20",
    img: "https://i.imgur.com/GXEUWgG.png",
    price: 900.0,
    description:
      "Multiple Card Holders key ring holder & many Pockets for Holding Money & Other Necessary Goods.",
    color: "Black Leather",
  },
];
